baseURL: https://example.com
languageCode: en-us
title: Andrew's Blog
theme: Minii

params:
  description: A simple blog created with Hugo
  author: Andrew
  
taxonomies:
  category: categories
  tag: tags

menu:
  main:
    - name: Blog
      url: /blog/
      weight: 1
    - name: RSS
      url: /index.xml
      weight: 2
    - name: Twitter
      url: https://twitter.com/yourusername
      weight: 3
    - name: Email
      url: mailto:you@example.com
      weight: 4
